branches:
  only:
    - master

before_install:
script: make
language: cpp
compiler: g++

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "CJWhPy7PVwlxVG4x8wX7GqwomwgygQA28CIdNzG3a//4t+r2HEsCkSRSK+9EDpqbtFRKR6Zmlmo4NJrLkriZNSX+zgzRDa7G+fetu7Iw8B1jUWnEAKEZJMzV9wKeJQjr803SukN01XRhkOAccyRoKKyQWhqdo4jmUXEnM8MNscAYdoztPykwBOqCYsx11ulzEyIO/KfUETtyil4mdOq5b8eSo45VGYHQTH+urjwEygdtZJxi7+QY74dCPDwVbrPAgE0KVobJZTm54WeDRaQZaBLFdjKh0MH67tUTXtM2m6csb2RSvOgpuB9yFEaSvhVMo/WUU+tbA+t7WS5fkyidNQ26+/4rT9UU54RYR7ZUcIy8D6Bn9hpG+M4nHul7uj4dXECkpITcMTohUVA0s3mAA4pGL0FXql/I0T6sxkxMb1njnZaD2qiO9TA3OrHTQbLclFBzjBk8btXv7l61UlzCocebpJaL6qjBvmvl4vTV/HJBOiyVHUAqYqUu7OT1zicCRYDgd7ZZrbKEud6/zv91wYrydwRIE9A4hIslm+1JXvttuduvALzVkHr0K1CDVn5gPbPDyUj5tUzF6p1iZUEoGgEGlJl0jD/cP02sUL6jxmE8r1jT2vR2iaiyca6XR42qOjKXFqhrWQDyijAH0eFywL6obe2cpQ8gaRj7gvxYcx0="

before_install:
  - echo -n | openssl s_client -connect https://scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

addons:
  coverity_scan:
    project:
      name: "FBLipke/Namiono-Server"
      description: ""
    notification_email: contact-bln@fblipke.de
    build_command: "make"
    branch_pattern: master
