branches:
  only:
    - master

before_install:
script: make
language: cpp
compiler: g++

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "GRmaY+5UArQHGeF2vmqwu0U8svzJA+x+fbMNxlA4MDnsHQuKmmfsrAWCdC4jiP6BmyIj4jKAQcFzPB4plZUt5yuTv/L6SfX6sOJDBaakmtXL3TWIhPx8MRUu/TvYq37OiObJWb04IollLra6gBKxQxzrdKQzzi1fhfJOodX8Huf2CNnyFAJ9XpuXLFzWrYXp94gqh2CoUdHUaNEpJdC9kezq1YzzWOgAmd+wiNYZmpGWFssKIodNjiEOshqaxDWYrmP0Q1QniUl9OqLSnFsRJMHGD4/CF01cSSCb1ZAB/0g+7APNqE4ZS+vrzcU97PJZbpiqZDlIjcwm9DaVaj6a7UrWSmUjl/DrnF19MnMoVZ+qgu5U5fPN3sls6UnROHXjOpYINNZpv2PKs/F6uBoJgSpjfc3zAplfzbh4f/V5+U625Kk/SeGXg1abRqH5SVzu/IMiqF9c8II9cfvSq3UtPeU+Efm9KIzn6gD4P0wmU/IE+TA273F42uF81i6xEW9GrjuQYRxxoTNWqFGebjDcuUWGrqH/7eATLgLWk1IBXqESdsMZzfUS9XQt2TqCazMxCy1izA5UGyXgU4GW0gn7LPQ6QeWux79bE8kqzwIIC0UtvHSC5olCN4LwINETmzJXyOZr/foXWfWS0PTinw6ZdpNYOpweKY20TGDki+OmDyc="

before_install:
  - echo -n | openssl s_client -connect https://scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

addons:
  coverity_scan:
    project:
      name: "FBLipke/Namiono-Server"
      description: "Network Boot Daemon"
    notification_email: contact-bln@fblipke.de
    build_command_prepend: "make"
    build_command: "make"
    branch_pattern: master
